### ISSUE TITLE
Share training data or model?

### ISSUE THREAD

**Issue by hkristen** [UNITAR-UNOSAT/UNOSAT-AI-Based-Rapid-Mapping-Service#1]
Great publication and amazing results. Also thank you for sharing everything so openly! 

Is there a chance that you can share your training data or final fast.ai model? That would be great :)
I can provide space to host it, if needed!

Cheers,
Harald

**Comment by enemni** [comment]
Hello Harald, 

Thanks for your comment. We are currently working to create an end-to-end pipeline and also a docker for easy deployment including the required post-processing.  We don't have a release date yet, but most of the data used are already on the HDX UNOSAT page https://data.humdata.org/organization/un-operational-satellite-appplications-programme-unosat.  We are also planning to share the training data within a challenge-framework. 

Best, 

Edoardo
