### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by KonstantinosF** [UNITAR-UNOSAT/UNOSAT-AI-Based-Rapid-Mapping-Service#2]
It would be very interesting if you could upload the dataset or a fraction of it, so we could reproduce the expirements. Thank you

**Comment by ddbuscombe** [comment]
Yes, me too. Thanks in advance

**Comment by SRoche14** [comment]
I would also like to see the dataset. This link does not work: http://floods.unosat.org/geoportal/catalog/main/home.page

**Comment by enemni** [comment]
Thank you for reaching out and expressing your interest in our paper on flood mapping with SAR. However, I apologize for the inconvenience regarding the broken link to the dataset. We updated it and you can find the data in the [Prepare the data](https://github.com/UNITAR-UNOSAT/UNOSAT-AI-Based-Rapid-Mapping-Service#prepare-the-data) section.
